[book]
title = "Izohli Atamalar Lug ªati"
authors = ["chapani"]

[preprocessor.fs-summary]
index_file_name = ["00.md", "README.md", "uzbek-index.md", "index.md"]

[output.html]
mathjax-support = true

