[book]
title = "Izohli Atamalar LuÄŸati"
authors = ["chapani"]

[output.html]
mathjax-support = true
additional-css = ["assets/ial.css"]
additional-js = ["assets/ial.js"]

[preprocessor.atama-orinlovchi]
command = "mdbook-tiqmalarim/target/release/atama-orinlovchi"

[preprocessor.atama-tamgalovchi]
command = "mdbook-tiqmalarim/target/release/atama-tamgalovchi"

[preprocessor.atamalar-kirish]
command = "mdbook-tiqmalarim/target/release/atamalar-kirish"
