[package]
name = "atama-orinlovchi"
version = "0.1.1"
edition = "2024"

[dependencies]
mdbook = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
atama-umumiy = { path = "../atama-umumiy" }

[dev-dependencies]
tempfile = "3"
