[package]
name = "atama-tamgalovchi"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
fancy-regex = "0.13"
mdbook = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
atama-umumiy = { path = "../atama-umumiy" }

[dev-dependencies]
tempfile = "3.8"
