name: Lug'atni GitHub Pages'da Ishga Solish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dafinaga o'tish
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rust Toolchain' o'rnatish
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Qaramliklari
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            mdbook-tiqmalarim/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('mdbook-tiqmalarim/Cargo.lock') }}

      - name: mdBook'ni o'rnatish
        run: |
          cargo install mdbook --no-default-features --features search --locked

      - name: Xos oldishlovchilarni o'rnatish
        # Bu mdbook-tiqmalarim ichidagi barcha oldishlovchilarni o'rnatadi
        run: cargo build --release --manifest-path mdbook-tiqmalarim/Cargo.toml

      - name: mdBook'ni qurish
        run: mdbook build

      - name: Hosila Sahifalarni yuklash
        uses: actions/upload-pages-artifact@v3
        with:
          path: book

      - name: GitHub Pages'da ishga solish
        id: deployment
        uses: actions/deploy-pages@v4
